### ISSUE TITLE
Provide screenshots in the README

### ISSUE THREAD

**Issue by andreypopp** [igorgladkoborodov/vv#2]
Apologize if that's something you think is too early to be done but it would be nice to have screenshots in the README of the running vv instance.

Thanks! It's always exciting to see another frontend for Vim/Neovim to appear!

**Comment by igorgladkoborodov** [comment]
Sure, that makes a lot of sense. I have a couple of rendering bugs to fix and I want to provide screenshots and a screencast covering some app features.
