### ISSUE TITLE
ALE syntax checker

### ISSUE THREAD

**Issue by dgorodnichy** [igorgladkoborodov/vv#3]
Hi, I have issue with [ale](https://github.com/w0rp/ale) plugin I use my regular vimrc from original vim([vimrc](https://github.com/dgorodnichy/dotfiles/blob/master/vim/.vimrc)) and ALE is not working. It doesn't mark syntax errors and :ALEFix doesn't fix warnings. I tried with another electron VIMs(oni vim for example) and they also doesn't support this plugin.

**Comment by dgorodnichy** [comment]
Not actual any more.

**Comment by igorgladkoborodov** [comment]
Sorry for late response. Ale works fine in Neovim and VV. I personally use it. Does it work in terminal nvim? Here is my vimrc you can check my ale setup: https://github.com/igorgladkoborodov/nvimconfig/blob/master/init.vim
