### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by dgorodnichy** [igorgladkoborodov/vv#4]
When I apply Fullscreen mode, vv opens on current workspace and doesn't hide applications panel. I expect that its behavior will be like Slack(opens on new workspace). 

![unspecified](https://user-images.githubusercontent.com/871518/43773377-3444be14-9a4e-11e8-94d0-ca0713fa5905.png)

**Comment by igorgladkoborodov** [comment]
VV has simple fullscreen by default. You can use the system default fullscreen mode by
```
:VVset simplefullscreen=0
```
