### ISSUE TITLE
Use of --headless

### ISSUE THREAD

**Issue by justinmk** [igorgladkoborodov/vv#6]
I noticed that VV uses `--headless`: https://github.com/igorgladkoborodov/vv/blob/c588d7e3676564bea17b2d526df5db9a6cddb501/src/renderer/nvim/nvim.js#L202

In https://github.com/neovim/neovim/pull/9024 (Nvim 0.3.2) we're considering changing the meaning of `--headless`. It may not be necessary and may improve behavior if VV uses `--embed` without also specifying `--headless`.

Note that the `nvim_get_api_info()` metadat includes a `version` field which can be checked to decide whether to use `--embed` in Nvim 0.3.2+

**Comment by igorgladkoborodov** [comment]
Thank you for info. I will check it later today.
